name: Metrics Generator
on:
  push:
  schedule:
    - cron: "0 0 * * 0"
  workflow_dispatch:

permissions: 
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Metrics embed
        uses: lowlighter/metrics@v3.34
        with:
          filename: docs/metrics.svg
          token: ${{ github.token }}
          config_timezone: Asia/Shanghai
          plugin_lines: true
          plugin_calendar: true
          plugin_wakatime: true
          plugin_wakatime_token: ${{ secrets.WAKATIMETOKEN }}  
          plugin_wakatime_sections: time, languages, languages-graphs, editors, os
          plugin_languages: true
          plugin_languages_indepth: true
